# Generated by Django 4.2.15 on 2024-08-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readonlymodelviewset', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
