# Generated by Django 4.2.17 on 2024-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("roll", models.IntegerField()),
                ("city", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
